### PR TITLE
Update makefile

### PR DESCRIPTION
**Pull request by KevinJoiner**

### CODE REVIEW

**Comment by elffjs** [comment]
This looks like a good idea, thanks.

My knowledge of make is all copy paste so I'll just assume the syntax is great.

**Review by Allyson-English — APPROVED** [review]

**Comment by elffjs** [comment]
By the way, Goose has a command `goose fix` that makes the migrations sequential.

**Comment by elffjs** [comment]
Okay yeah check this out:

https://github.com/DIMO-Network/identity-api/blob/7341b00f13e9230342d14eb420d7c8af39524e6d/Makefile#L13

I think it got removed when I freaked out and replaced everything with the standard Benthos Makefile copy-paste because I couldn't get the container to build. But I think it was a good idea.

**Comment by KevinJoiner** [comment]
ooh goose fix is cool. I added the `-s` to the make file, which will knew migration files sequential.

**Comment by KevinJoiner** [comment]
@elffjs That help command is super cool!

**Review by elffjs — APPROVED** [review]

**Comment by elffjs** [comment]
> ooh goose fix is cool. I added the `-s` to the make file, which will knew migration files sequential.

Didn't know that flag. That's even better.

**Pull request merged**
