### PR TITLE
[SM-994] make model filter case insensitive

### PR DESCRIPTION
**Pull request by Asfiroth**
- Make tableland model filter case insensitive.

### CODE REVIEW

**Review by Allyson-English — APPROVED** [review]

**Review by JamesReate — APPROVED** [review]
let's try it out

**Comment by elffjs** [comment]
Have you tested this? Can you present any evidence that it works?

**Comment by elffjs** [comment]
If it does indeed work: We should update the docs on the filter to tell people.

**Comment by Asfiroth** [comment]
Yup, this query: `https://testnets.tableland.network/api/v1/query?statement=select * from _80002_8 where model = '4c' COLLATE NOCASE` returns data
Screen Shot 2024-07-23 at 14 18 06 PM

Same query without `COLLATE NOCASE` returns nothing
Screen Shot 2024-07-23 at 14 19 19 PM

since the exacto Model for Alfa Romeo would be '4C'  with first query is working with '4c'

**Comment by elffjs** [comment]
I want to see it work in the context of identity-api.

We merged it anyway so I guess I can test myself.

**Pull request merged**
